# Generated by Django 5.0.3 on 2024-03-16 10:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('dad_name', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2024, 3, 16, 10, 10, 47, 106788, tzinfo=datetime.timezone.utc), null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 16, 10, 10, 47, 106788, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(default='uchirilgan user', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bemor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
