# Generated by Django 5.0.3 on 2024-03-16 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 16, 10, 11, 11, 774877, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
