# Generated by Django 5.0.3 on 2024-03-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0002_alter_bemor_created_at_alter_bemor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemor',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
