# Generated by Django 5.0.3 on 2024-03-16 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klinika', '0003_alter_bemor_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tashxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tashxis', models.TextField(blank=True, null=True)),
                ('lecheniya', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('narx', models.PositiveIntegerField(default=0)),
                ('tuladi', models.PositiveIntegerField(default=0)),
                ('qoldi', models.PositiveIntegerField(default=0)),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klinika.bemor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
